In [14]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in .\venv\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\venv\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in .\venv\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\venv\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [51]:
df = pd.read_csv("Datasets/student_binary_classification.csv")
df

    StudyHours Result
0          1.0   Fail
1          2.0   Fail
2          2.5   Fail
3          3.0   Fail
4          3.5   Fail
5          4.0   Pass
6          4.5   Pass
7          5.0   Pass
8          5.5   Pass
9          6.0   Pass
10         7.0   Pass
11         8.0   Pass

In [52]:
df["Result"] = df["Result"].map ({
    "Fail" : 0,
    "Pass" : 1
})
df["Result"]

0     0
1     0
2     0
3     0
4     0
5     1
6     1
7     1
8     1
9     1
10    1
11    1
Name: Result, dtype: int64

In [55]:
X = df[["StudyHours"]]
y = df["Result"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(predictions)
print(X_test)
print(y_test)
new_student  = pd.DataFrame({
    "StudyHours" : [5.0]
})
predictions = model.predict(new_student)
print(predictions)

[1 1 0]
    StudyHours
10         7.0
9          6.0
0          1.0
10    1
9     1
0     0
Name: Result, dtype: int64
[1]

In [21]:
df = pd.read_csv("Datasets/student_multiclass_multiple_features.csv")
df

    Student  StudyHours  Attendance  PreviousMarks   Result
0     Aarav           1          55             28     Fail
1      Sita           2          60             32     Fail
2       Ram           2          65             36     Fail
3    Anisha           3          70             40     Fail
4     Rohan           3          72             43     Fail
5     Priya           4          75             48  Average
6     Kiran           4          78             52  Average
7     Nabin           5          80             56  Average
8     Suman           5          82             60  Average
9    Alisha           5          84             63  Average
10   Bikash           6          86             67     Good
11   Sabina           6          88             70     Good
12   Roshan           6          90             73     Good
13     Puja           7          91             76     Good
14   Manish           7          92             79     Good
15     Rita           7          93             82     Good
16    Deepa           8          94             84     Good
17   Sanjay           8          95             87     Good
18   Kushal           8          96             89     Good
19   Aakash           9          97             91     Good
20     Bina           9          90             75     Good
21  Nischal           9          94             85     Good
22    Rekha          10          98             93     Good
23    Sagar          10          99             95     Good
24     Mina          10          96             90     Good

In [22]:
df["Result"] = df["Result"].map({
    "Fail" : 0,
    "Average" : 1,
    "Good":2
})
print(df["Result"])

0     0
1     0
2     0
3     0
4     0
5     1
6     1
7     1
8     1
9     1
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
Name: Result, dtype: int64

In [25]:
X = df[["StudyHours", "Attendance", "PreviousMarks"]]
y = df["Result"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(predictions)
print(X_test)
print(y_test)

print(classification_report(y_test, predictions))

[1 2 0 2 2]
    StudyHours  Attendance  PreviousMarks
8            5          82             60
16           8          94             84
0            1          55             28
23          10          99             95
11           6          88             70
8     1
16    2
0     0
23    2
11    2
Name: Result, dtype: int64
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         3

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5